name: azerox
description: A new Flutter project.

publish_to: 'none'

version: 6.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  dio: ^4.0.4
  intl: ^0.17.0
  flutter_social_content_share: ^1.0.2
  flutter_facebook_auth: ^3.5.7
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+8
  permission_handler: ^8.3.0
  audio_session: ^0.1.6+1
  flutter_sound: ^9.1.7
  flutter_sound_platform_interface: ^9.1.7
  record_mp3: ^3.0.0
  mask: ^1.0.2
  lazy_load_scrollview: ^1.1.0
  file_picker: ^4.5.1
  image_compression: ^1.0.3
  url_launcher: ^6.1.2
  flutter_widget_from_html_core: ^0.8.5+3
  image_cropper: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
