name: azerox
description: A new Flutter project.
version: 6.0.2+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.5.1
  dio: ^4.0.4
  intl: ^0.17.0
  # flutter_social_content_share: ^1.0.0 # TODO pacote quebrando no IOS
  # flutter_facebook_auth: ^3.5.7 # TODO pacote quebrando no IOS
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+8
  permission_handler: ^8.3.0
  flutter_sound: ^8.5.0
  # flutter_sound_platform_interface: ^9.1.7
  mask: ^1.0.2
  lazy_load_scrollview: ^1.1.0
  file_picker: ^4.5.1
  image_compression: ^1.0.3
  url_launcher: ^6.1.2
  flutter_widget_from_html_core: ^0.8.5+3
  image_cropper: ^2.0.2
  just_audio: ^0.9.27
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
